version: '3.7'
services:
  web:
    build: .
    entrypoint: /usr/src/app/entrypoint-waf.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  proxy:
    build: .
    command: python waf.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - db
      - web
      - redis
  haproxy:
    image: "haproxy:2.2-alpine"
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./cert:/etc/ssl/certs/
  redis:
    image: redis:alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=waf
      - POSTGRES_PASSWORD=simple-waf
      - POSTGRES_DB=simple-waf
    ports:
      - 5432:5432
volumes:
  postgres_data:
