{
 "title": "WAF",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  id\nFROM main_events\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Popular regular",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  reg AS metric,\n  id\nFROM main_events\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "IP in ban",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "query": "KEYS '*'", "type": "cli" }
   ]
  },
  {
   "title": "Attack Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  method AS metric,\n  id\nFROM main_events\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Attack Location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  location AS metric,\n  id\nFROM main_events\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Ip - Attack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  ip AS metric,\n  id\nFROM main_events\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Redis Hash Stat",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    { "command": "info", "section": "commandstats", "type": "command" }
   ]
  }
 ]
}