# Generated by Django 3.0.4 on 2020-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='stable',
            field=models.BooleanField(default=True),
        ),
    ]
