# Generated by Django 3.0.4 on 2020-03-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blacklist_stable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('url', models.CharField(max_length=255)),
                ('args', models.TextField()),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('cookie', models.TextField()),
                ('method', models.CharField(max_length=6)),
                ('ip', models.CharField(max_length=15)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AttackType')),
            ],
        ),
    ]
