# Generated by Django 3.0.4 on 2020-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reg',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
