# Generated by Django 3.0.4 on 2020-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_events_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='args',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='body',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='url',
            field=models.BooleanField(default=False),
        ),
    ]
