# Generated by Django 3.0.4 on 2020-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200320_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='BODY', max_length=25),
            preserve_default=False,
        ),
    ]
