# Generated by Django 3.0.4 on 2020-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='127.0.0.1:81', max_length=255)),
                ('port', models.IntegerField(default=80, verbose_name='порт')),
                ('x_frame_option', models.BooleanField(default=True, verbose_name='запрет встраивания в фреймы')),
                ('signature_analysis', models.BooleanField(default=True, verbose_name='сигнатурный анализ')),
                ('xss_browser_protection', models.BooleanField(default=False, verbose_name='встроенная защита браузера от XSS')),
                ('no_sniff', models.BooleanField(default=True, verbose_name='запрет угадывания content-type')),
                ('content_security_policy_self', models.BooleanField(default=False, verbose_name='строгая политика CSP')),
                ('hide_server', models.BooleanField(default=True, verbose_name='скрытие сервера')),
                ('hide_x_powered_by', models.BooleanField(default=True, verbose_name='скрытие ПО сервера')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterModelOptions(
            name='attacktype',
            options={'verbose_name': 'атака', 'verbose_name_plural': 'Названия атак'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'правило', 'verbose_name_plural': 'Список правил'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reg',
            field=models.CharField(max_length=200, verbose_name='Регулярное выражение'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='stable',
            field=models.BooleanField(default=True, verbose_name='Точная строка'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
