# Generated by Django 3.0.4 on 2020-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200330_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='cert_file',
            field=models.CharField(default='certs/mydomain.crt', max_length=255, verbose_name='Файл сертификата'),
        ),
        migrations.AddField(
            model_name='configs',
            name='https',
            field=models.BooleanField(default=False, verbose_name='HTTPS'),
        ),
        migrations.AddField(
            model_name='configs',
            name='key_file',
            field=models.CharField(default='certs/mydomain.key', max_length=255, verbose_name='Ключ сертификата'),
        ),
        migrations.AddField(
            model_name='configs',
            name='strict_transport_security',
            field=models.BooleanField(default=False, verbose_name='добавить заголовок Strict-Transport-Security'),
        ),
    ]
