# Generated by Django 3.0.7 on 2020-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_configs_daemon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='reg',
            field=models.TextField(max_length=500, verbose_name='Регулярное выражение'),
        ),
        migrations.AlterField(
            model_name='configs',
            name='cert_file',
            field=models.CharField(default='/opt/simple-waf/certs/mydomain.crt', max_length=255, verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='configs',
            name='key_file',
            field=models.CharField(default='/opt/simple-waf/certs/mydomain.key', max_length=255, verbose_name='Ключ сертификата'),
        ),
    ]
