# Generated by Django 3.0.7 on 2020-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201006_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='cert_file',
            field=models.CharField(default='certs/mydomain.crt', max_length=255, verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='configs',
            name='key_file',
            field=models.CharField(default='certs/mydomain.key', max_length=255, verbose_name='Ключ сертификата'),
        ),
    ]
