# Generated by Django 3.0.7 on 2020-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201006_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='127.0.0.1', max_length=255)),
                ('port', models.IntegerField(default=80, verbose_name='порт')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления сервера')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления конфигурации')),
            ],
            options={
                'verbose_name': 'прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
    ]
