# Generated by Django 3.0.7 on 2020-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configs',
            name='daemon_status',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего подключения'),
        ),
    ]
