# Generated by Django 3.0.7 on 2020-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_events_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='ban_enable',
            field=models.BooleanField(default=False, verbose_name='Автоматический бан:'),
        ),
        migrations.AddField(
            model_name='configs',
            name='ban_time',
            field=models.IntegerField(default=60, verbose_name='Время бана (сек):'),
        ),
        migrations.AddField(
            model_name='configs',
            name='head_hash',
            field=models.BooleanField(default=True, verbose_name='Хэширование заголовков запроса'),
        ),
    ]
